import os
import sys
from typing import List, Dict, Any

# Ensure imports work from current directory regardless of execution context
project_root = os.path.dirname(os.path.abspath(__file__))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

from src.config import Config
from src.core.state import AgentState
from src.core.gemini import GeminiCore
from src.mcp.linear import parse_linear_issue, fetch_issue_details
from src.mcp.github import get_repo_structure, get_pr_diff
from src.mcp.db_schema import parse_schema_to_markdown, get_database_schema
from src.agents.ba import check_conflicts
# นำเข้าฟังก์ชันจาก SA Agent ที่พึ่งสร้างในตั๋วงาน Task 2.2
from src.agents.sa import review_architecture_compliance
from src.agents.ux import review_ui_spec
from src.agents.dev import generate_code_files
from src.agents.qa import generate_test_matrix
from src.agents.pm import calculate_base_risk_score, analyze_sprint_risk

# Mock Data for Local Validation
MOCK_LINEAR_JSON = {
    "identifier": "PROJ-777",
    "title": "Implement API Security Headers and CORS Policy",
    "description": "Configure HTTP security headers (Helmet, CORS policies, X-Frame-Options) across all endpoints.",
    "state": {"name": "In Progress"},
    "assignee": {"name": "Dev Agent"},
    "priorityLabel": "High",
    "labels": {
        "nodes": [
            {"name": "backend"},
            {"name": "security"}
        ]
    },
    "comments": {
        "nodes": [
            {
                "user": {"name": "QA Agent"},
                "body": "Please ensure to check RBAC permissions on CORS preflight requests."
            }
        ]
    }
}

MOCK_DB_METADATA = [
    {
        "table_name": "users",
        "column_name": "id",
        "data_type": "integer",
        "is_nullable": "NO",
        "constraint_type": "PRIMARY KEY"
    },
    {
        "table_name": "users",
        "column_name": "email",
        "data_type": "character varying",
        "is_nullable": "NO",
        "constraint_type": "UNIQUE"
    },
    {
        "table_name": "users",
        "column_name": "password_hash",
        "data_type": "character varying",
        "is_nullable": "NO",
        "constraint_type": None
    },
    {
        "table_name": "api_logs",
        "column_name": "id",
        "data_type": "uuid",
        "is_nullable": "NO",
        "constraint_type": "PRIMARY KEY"
    },
    {
        "table_name": "api_logs",
        "column_name": "headers",
        "data_type": "jsonb",
        "is_nullable": "YES",
        "constraint_type": None
    }
]


def safe_write_generated_files(dev_report: dict, overwrite_allowed: bool = False) -> None:
    """
    Safe-Write Check mechanism to safely write code files generated by the Dev Agent on disk.
    Ensures existing files are not accidentally overwritten unless explicitly permitted.
    """
    base_dir = "d:/AI-AgentProject/"
    
    if not dev_report or "generated_files" not in dev_report:
        print("[SAFE-WRITE SKIP] No generated files found in the report.")
        return

    for file_item in dev_report.get("generated_files", []):
        rel_path = file_item.get("file_path")
        code_content = file_item.get("code_content", "")

        if not rel_path:
            continue

        # Resolve target path relative to the specific project root
        resolved_path = os.path.normpath(os.path.join(base_dir, rel_path))

        # Ensure parent directories exist
        parent_dir = os.path.dirname(resolved_path)
        os.makedirs(parent_dir, exist_ok=True)

        # Check if file already exists on disk
        if os.path.exists(resolved_path) and not overwrite_allowed:
            print(f"[SAFE-WRITE BLOCKED] File already exists: {resolved_path}")
        else:
            try:
                with open(resolved_path, "w", encoding="utf-8") as f:
                    f.write(code_content)
                print(f"[SAFE-WRITE SUCCESS] Written: {resolved_path}")
            except Exception as e:
                print(f"[SAFE-WRITE ERROR] Failed to write {resolved_path}: {str(e)}")


def export_test_cases_to_management_tool(qa_report: dict) -> None:
    """
    [Human/AI Connector] จำลองการนำข้อความ Test Cases หรือ JSON ที่ QA Agent เจนฯ ได้
    แปลงเป็น Payload แล้วยิงผ่าน HTTP POST API เข้าสู่ Test Management Tool (เช่น Jira/TestRail)
    """
    print("\n[CONNECTOR] เริ่มกระบวนการส่งออกแผนการทดสอบเข้าสู่ Test Management Tool...")
    
    if not qa_report or "test_cases" not in qa_report:
        print("[CONNECTOR SKIP] ไม่พบข้อมูลเทสเคสในรายงานสำหรับการส่งออก")
        return
        
    # จำลองการจัดโครงสร้างเพื่อส่งเข้าสู่ระบบ REST API ภายนอก
    for tc in qa_report.get("test_cases", []):
        tc_id = tc.get("id", "TC-UNKNOWN")
        title = tc.get("title", "No Title")
        category = tc.get("category", "General")
        
        # แสดงผลการจัดเตรียมและส่งสำเร็จผ่านหน้าจอ Console
        print(f"[API HTTP 201 Created] บันทึกเทสเคสสำเร็จ -> ยิงข้อมูลเคส {tc_id}: [{category}] {title} เข้าสู่ระบบคลังทดสอบเรียบร้อย")


def run_local_validation():
    """
    Simulates Phase 1 (Foundation) & Phase 2 pipeline locally
    to ensure the LangGraph state sharing, environment configurations, and Gemini API bindings work.
    """
    print("==================================================")
    print("      STARTING AGENTIC SDLC LOCAL VALIDATION     ")
    print("==================================================")
    
    # 1. Initialize State and Shared Core
    state: AgentState = {
        "linear_issue_id": "PROJ-INIT",
        "current_api_spec": None,
        "risk_score": 0.0,
        "approval_status": "PENDING",
        "issue_details": None,
        "repo_structure": None,
        "pr_diff": None,
        "db_schema": None,
        "logs": []
    }
    print("\n[OK] Initialized LangGraph AgentState with default monitoring values.")
    
    # Check Gemini API Connection
    print(f"Checking environment variables... API KEY Present: {bool(Config.GEMINI_API_KEY)}")
    
    # 2. Simulate Phase 1: Context Layer Parsing (Linear/GitHub/DB Metadata Parsing Tools)
    print("\n--- Simulating Phase 1: Context Tools Parsing ---")
    
    # Linear Data Mock Processing
    linear_markdown = parse_linear_issue(MOCK_LINEAR_JSON)
    state["linear_issue_id"] = MOCK_LINEAR_JSON["identifier"]
    print(f"[OK] Parsed Linear Issue Metadata to Markdown (Length: {len(linear_markdown)} chars)")
    
    # DB Schema Metadata Mock Processing
    db_schema_markdown = parse_schema_to_markdown(MOCK_DB_METADATA)
    print(f"[OK] Parsed Database Schema Metadata to Markdown (Length: {len(db_schema_markdown)} chars)")
    
    # GitHub Repo Mock Processing
    mock_repo_structure = "src/\n  core/\n    gemini.py\n    state.py\n  agents/\n    ba.py\n    sa.py\nmain.py"
    print(f"[OK] Mocked GitHub Repository Structure Context:\n{mock_repo_structure}")

    # 3. Simulate Phase 2: Core Role-Based Agent - BA Agent Conflict Checker
    print("\n[TEST] Testing BA Agent Conflict Checker (AI Sub-task)...")
    mock_history = [
        "Historical Ticket #1: The system authentication must enforce OAuth2 token verification. Standard password logins are disabled for security reasons.",
        "Historical Ticket #2: Database schema for user requires unique email indexing.",
        f"Database Context:\n{db_schema_markdown}"
    ]
    
    # This requirement directly contradicts Historical Ticket #1
    mock_contradicting_req = "Requirement: Allow users to log in using standard username and password fields only. Disable OAuth2 entirely to simplify user onboarding."
    
    if Config.GEMINI_API_KEY:
        try:
            print("Sending conflicting requirements to BA Agent (using gemini-2.5-pro)...")
            ba_report = check_conflicts(mock_contradicting_req, mock_history)
            print("-" * 40)
            print("BA Agent Analysis Report (Structured Output):")
            
            if isinstance(ba_report, dict):
                import json
                print(json.dumps(ba_report, indent=2, ensure_ascii=False))
            else:
                print(str(ba_report).strip())
                
            print("-" * 40)
        except Exception as e:
            print(f"[ERROR] BA Agent conflict check failed: {str(e)}")
    else:
        print("[SKIP] Skipping live Gemini call for BA Agent. Mock input setup:")

    # 4. Simulate Phase 2: Core Role-Based Agent - SA Agent Architecture Compliance Review
    print("\n[TEST] Testing SA Agent Architecture Compliance Review (AI/Human Sub-task)...")
    
    # เจตนาจำลอง Requirement ที่จงใจละเมิดกฎสถาปัตยกรรม (ชื่อคลาสผิด ไม่ยอมใช้ Service Layer และคืนรูปแบบ API ผิดมาตรฐาน)
    mock_bad_architecture_req = """
    Requirement: Create a new endpoint named '/api/v1/quick-login' directly inside a class named 'UserAuthenticator' without creating a Service class.
    If the authentication fails, the endpoint should return a raw plain text string message like 'Failed to log in' accompanied by HTTP Status Code 400.
    """
    
    if Config.GEMINI_API_KEY:
        try:
            print("Sending requirements to SA Agent to check architectural rules...")
            sa_report = review_architecture_compliance(mock_bad_architecture_req)
            print("-" * 40)
            print("SA Agent Architecture Compliance Report (Structured Output):")
            
            if isinstance(sa_report, dict):
                import json
                print(json.dumps(sa_report, indent=2, ensure_ascii=False))
            else:
                print(str(sa_report).strip())
                
            print("-" * 40)
        except Exception as e:
            print(f"[ERROR] SA Agent architecture review failed: {str(e)}")
    else:
        print("[SKIP] Skipping live Gemini call for SA Agent. Ensure GEMINI_API_KEY is configured.")

    # 5. Simulate Phase 2: Core Role-Based Agent - UX Agent State & Component Mapper
    print("\n[TEST] Testing UX Agent Design Tokens & State Mapping (AI Sub-task)...")
    mock_ux_req = "Requirement: Design a responsive user profile dashboard showing user details, subscription badge, and past invoices table."
    mock_storybook_context = "Storybook Atomic Tokens:\n- Atoms/Buttons: primary-btn, secondary-btn\n- Atoms/Badges: success-badge, alert-badge\n- Organisms/Tables: data-striped-table"
    
    if Config.GEMINI_API_KEY:
        try:
            print("Sending UX request to UX Agent...")
            combined_ux_input = f"{mock_ux_req}\n\n[Storybook Context]:\n{mock_storybook_context}"
            ux_report = review_ui_spec(combined_ux_input)
            print("-" * 40)
            print("UX Agent Analysis Report (Structured Output):")
            if isinstance(ux_report, dict):
                import json
                print(json.dumps(ux_report, indent=2, ensure_ascii=False))
            else:
                print(str(ux_report).strip())
            print("-" * 40)
        except Exception as e:
            print(f"[ERROR] UX Agent review failed: {str(e)}")
    else:
        print("[SKIP] Skipping live Gemini call for UX Agent. Ensure GEMINI_API_KEY is configured.")

    # 6. Simulate Phase 2: Core Role-Based Agent - Dev Agent Boilerplate Generator
    print("\n[TEST] Testing Dev Agent Code Generation Pipeline (AI Sub-task)...")
    mock_api_spec = "OpenAPI 3.0 Spec:\n- GET /api/v1/profile: returns 200 OK with UserProfile object."
    mock_dev_req = "Requirement: Create the profile controller layer. Extract fields: name, email and avatar of the logged in user."
    
    if Config.GEMINI_API_KEY:
        try:
            print("Sending specs to Dev Agent to generate boilerplate...")
            dev_report = generate_code_files(mock_api_spec, mock_repo_structure, mock_dev_req)
            print("-" * 40)
            print("Dev Agent Boilerplate Report (Structured Output):")
            
            if isinstance(dev_report, dict):
                import json
                for file_info in dev_report.get("generated_files", []):
                    path = file_info.get("file_path", "unknown.py")
                    content = file_info.get("code_content", "")
                    preview = "\n".join(content.split("\n")[:8])
                    print(f"File Path: {path}")
                    print(f"Code Preview:\n{preview}\n... (truncated)")
                    print("-" * 20)
            else:
                print(str(dev_report).strip())
                
            print("-" * 40)
        except Exception as e:
            print(f"[ERROR] Dev Agent code generation failed: {str(e)}")
    else:
        print("[SKIP] Skipping live Gemini call for Dev Agent. Ensure GEMINI_API_KEY is configured.")

    # 7. Simulate Phase 2: Dev Agent - Safe-Write Check Mechanism Execution
    print("\n[TEST] Testing Safe-Write Check Mechanism (Human/AI Governance Gateway)...")
    mock_dev_report_for_write = {
        "generated_files": [
            {
                "file_path": "src/controllers/profile_controller.py",
                "code_content": "# Generated Profile Controller\nclass ProfileController:\n    def get_profile(self):\n        pass\n"
            }
        ]
    }
    print("Triggering safe_write_generated_files with overwrite_allowed=False...")
    safe_write_generated_files(mock_dev_report_for_write, overwrite_allowed=False)

    # 8. Simulate Phase 2: QA Agent - Test Specification Matrix & Automation Connector
    print("\n[TEST] Testing QA Agent Matrix Generation & Automation Connector (AI/Human Sub-task)...")
    mock_qa_req = "Requirement: Develop the registration form endpoint. Validates email unique constraints and returns standardized error object if validation fails."
    
    if Config.GEMINI_API_KEY:
        try:
            print("Sending specs to QA Agent to generate Test Matrix...")
            qa_report = generate_test_matrix(mock_api_spec, mock_qa_req)
            print("-" * 40)
            print("QA Agent Test Matrix Report (Structured Output Preview):")
            
            if isinstance(qa_report, dict):
                import json
                # แสดงข้อมูลเคสเบื้องต้นใน log
                print(f"พบเทสเคสทั้งหมดจำนวน: {len(qa_report.get('test_cases', []))} เคส")
                # เรียกกลไก Mock Automation เพื่อส่งออกแผนการทดสอบเข้าคลังทันทีตามตั๋วงาน
                export_test_cases_to_management_tool(qa_report)
            else:
                print(str(qa_report).strip())
                
            print("-" * 40)
        except Exception as e:
            print(f"[ERROR] QA Agent test matrix generation failed: {str(e)}")
    else:
        print("[SKIP] Skipping live Gemini call for QA Agent. Ensure GEMINI_API_KEY is configured.")

    # 9. Simulate Phase 2: PM Agent - Agile Sprint Risk Assessment
    print("\n[TEST] Testing PM Agent Sprint Risk Radar (AI/Human Sub-task)...")
    mock_pm_req = "Requirement: Implement the secure high-throughput core payment gateway adapter."
    mock_comments = [
        "Dev Agent: I am stuck trying to configure OAuth2 credentials on the staging environment. Anyone got the keys?",
        "SA Agent: The current class structure violates single responsibility principle, please refactor before pushing.",
        "Dev Agent: Code refactoring is taking longer than expected. We might not make it into the sandbox environment yet. Blocking implementation.",
        "BA Agent: The payment flow is critical for the upcoming release, but security audit might take 2 weeks."
    ]
    
    base_score = calculate_base_risk_score(priority="High", conflict_count=1, comment_count=len(mock_comments))
    print(f"Calculated Baseline Risk Score (Human Logic): {base_score}%")
    
    if Config.GEMINI_API_KEY:
        try:
            print("Sending comments and base score to PM Agent to analyze sprint risk...")
            pm_report = analyze_sprint_risk(mock_pm_req, mock_comments, base_score)
            print("-" * 40)
            print("PM Agent Sprint Risk Report (Structured Output):")
            
            if isinstance(pm_report, dict):
                import json
                print(json.dumps(pm_report, indent=2, ensure_ascii=False))
            else:
                print(str(pm_report).strip())
                
            print("-" * 40)
        except Exception as e:
            print(f"[ERROR] PM Agent sprint risk analysis failed: {str(e)}")
    else:
        print("[SKIP] Skipping live Gemini call for PM Agent. Ensure GEMINI_API_KEY is configured.")

    print("\n==================================================")
    print("           VALIDATION PROCESS COMPLETED           ")
    print("==================================================")


if __name__ == "__main__":
    run_local_validation()